### PR TITLE
Testing a draft article

### PR DESCRIPTION
**Pull request by pabloromeo**

### CODE REVIEW

**Review by pabloromeo — COMMENTED** [review]
A comment

**Comment by pabloromeo** [comment]
Another

**Review by pabloromeo — COMMENTED** [review]
Another comment (edited)

**Review by pabloromeo — COMMENTED** [review]
Comment 2

**Review by pabloromeo — COMMENTED** [review]
Comment 3

**Review by pabloromeo — COMMENTED** [review]
Comment 4

**Review by pabloromeo — COMMENTED** [review]
Comment 5

**Review by pabloromeo — COMMENTED** [review]
Comment 7

**Review by ilaborde — APPROVED** [review]

**Review by pabloromeo — COMMENTED** [review]
Comment 8

**Review by ilaborde — APPROVED** [review]

**Pull request merged**
